version: '3.7'
services:
  monitored-app:
    build: .
    network_mode: host
  prometheus:
    image: prom/prometheus
    network_mode: host
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - monitored-app
  grafana:
    image: grafana/grafana
    network_mode: host
    restart: always
    depends_on:
      - prometheus